baseURL = "https://wwwid.org/"
languageCode = "en-ID"
title = "Modern Web Community Indonesia"
theme = "hugo-paper"
defaultContentLanguage="id"
enableRobotsTXT=true

[params]
    dateFormat="2 Jan 2006"
